spring.application.name=java-service
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/analyticore
spring.datasource.username=analyticore
spring.datasource.password=analyticore123
spring.datasource.driver-class-name=org.postgresql.Driver

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always